// Interactive portfolio system: dark technology workspace, glass surfaces, neon signal accents, lightweight CSS 3D, and recruiter-first information hierarchy.
import { FormEvent, useState } from "react";
import { ArrowDown, ArrowRight, Bot, CheckCircle2, Code2, Cpu, Database, Download, Github, GraduationCap, Linkedin, Mail, Menu, Network, Radar, Send, ShieldCheck, Sparkles, Terminal, X, Zap } from "lucide-react";

const profileLinks = [
  { label: "GitHub", href: "https://github.com/Chowhan-Praveen", icon: Github },
  { label: "LinkedIn", href: "https://www.linkedin.com/in/chowhan-praveen-498b0b33b", icon: Linkedin },
  { label: "LeetCode", href: "https://leetcode.com/u/chowhan-praveen/", icon: Code2 },
  { label: "CodeChef", href: "https://www.codechef.com/dashboard", icon: Terminal },
  { label: "Codeforces", href: "https://codeforces.com/profile/praveenchowhan1729", icon: Zap },
];

const skillGroups = [
  { title: "Programming", icon: Code2, color: "cyan", items: ["C", "C++", "Python", "Java", "JavaScript"] },
  { title: "Computer Science", icon: Network, color: "violet", items: ["Data Structures & Algorithms", "OOP", "DBMS", "Operating Systems", "Computer Networks"] },
  { title: "AI / ML", icon: Sparkles, color: "lime", items: ["Python", "Pandas", "NumPy", "Matplotlib", "Scikit-learn", "Machine Learning", "Data Analysis"] },
  { title: "Databases", icon: Database, color: "orange", items: ["SQL", "PL/SQL", "Oracle", "MongoDB", "MySQL"] },
  { title: "IoT / Embedded", icon: Cpu, color: "pink", items: ["Arduino", "ESP8266", "Raspberry Pi", "Sensors", "AWS IoT"] },
  { title: "Tools", icon: Terminal, color: "blue", items: ["Git", "GitHub", "VS Code", "Postman", "Vercel", "Render"] },
];

const projectCards = [
  { title: "VibePass", eyebrow: "FULL-STACK / EVENT SYSTEM", description: "A MERN event ticketing platform with separate customer and organizer roles, event discovery, tiered booking, capacity tracking, QR tickets, and sales analytics.", stack: ["React", "Node.js", "MongoDB", "JWT"], proof: "Auth portal · live capacity · QR wallet", href: "https://github.com/Chowhan-Praveen" },
  { title: "CloudCRM", eyebrow: "TYPESCRIPT / CUSTOMER SYSTEM", description: "A cloud-based CRM with separated frontend and backend layers for lead management, customer interactions, sales pipelines, authentication, and data workflows.", stack: ["TypeScript", "React", "Node.js", "SQL"], proof: "Separated layers · pipeline data · auth", href: "https://github.com/Chowhan-Praveen" },
  { title: "Basha Setu", eyebrow: "LANGUAGE / ACCESSIBILITY", description: "A regional language translation concept focused on converting Lambadi and Banjara into official languages to make communication more accessible.", stack: ["React", "Node.js", "Speech APIs"], proof: "Regional language focus · accessibility", href: "https://github.com/Chowhan-Praveen" },
];

const railwayStages = ["Railway component", "Laser marking", "QR code", "Mobile scanning", "AI recognition", "Traceability database", "Inspection history"];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [recruiterMode, setRecruiterMode] = useState(false);
  const [assistantOpen, setAssistantOpen] = useState(false);
  const [assistantQuestion, setAssistantQuestion] = useState("");
  const [messageSent, setMessageSent] = useState(false);

  const submitAssistantQuestion = (event: FormEvent) => {
    event.preventDefault();
    if (assistantQuestion.trim()) setAssistantOpen(true);
  };

  const submitContact = (event: FormEvent) => {
    event.preventDefault();
    setMessageSent(true);
  };

  return (
    <div className={`neo-site ${recruiterMode ? "recruiter-mode" : ""}`}>
      <header className="neo-nav">
        <a href="#home" className="neo-brand" aria-label="Praveen Chowhan home"><span className="neo-brand-mark">P<span>.</span></span><span className="neo-brand-copy"><b>PRAVEEN</b><small>SOFTWARE DEVELOPER</small></span></a>
        <nav className="neo-nav-links" aria-label="Primary navigation">{["About", "Skills", "Experience", "Projects", "Education", "Achievements", "Contact"].map((item) => <a key={item} href={`#${item.toLowerCase()}`}>{item}</a>)}</nav>
        <div className="neo-nav-actions"><button className={`recruiter-toggle ${recruiterMode ? "active" : ""}`} onClick={() => setRecruiterMode(!recruiterMode)} aria-pressed={recruiterMode}><Radar size={14} /> Recruiter mode</button><button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></div>
        {menuOpen && <div className="mobile-nav">{["About", "Skills", "Experience", "Projects", "Education", "Achievements", "Contact"].map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{item}</a>)}</div>}
      </header>

      <main>
        <section id="home" className="neo-hero section-pad">
          <div className="hero-copy"><div className="status-pill"><span className="pulse-dot" /> OPEN TO OPPORTUNITIES <span className="status-line" /></div><p className="section-kicker">01 / SOFTWARE DEVELOPER · HYDERABAD, INDIA</p><h1>Hi, I’m <span>Praveen<br className="desktop-break" /> Chowhan</span><i>.</i></h1><h2>Software Developer <em>|</em> AI/ML <em>|</em> IoT <em>|</em> Problem Solver</h2><p className="hero-intro">I build software, intelligent systems, and technology-driven solutions while continuously improving my problem-solving and development skills.</p><div className="hero-actions"><a href="#projects" className="neo-button primary">Inspect the systems <ArrowRight size={16} /></a><a href="/manus-storage/MYRESUME_69e3b508.pdf" target="_blank" rel="noreferrer" className="neo-button ghost">Download resume <Download size={16} /></a></div><div className="social-row">{profileLinks.map(({ label, href, icon: Icon }) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label}><Icon size={16} /><span>{label}</span></a>)}</div></div>
          <div className="hero-visual" aria-label="Abstract 3D technology workspace" role="img"><div className="scene-glow" /><div className="scene-ring ring-one" /><div className="scene-ring ring-two" /><div className="scene-orbit orbit-one"><span className="orbit-node node-cyan" /></div><div className="scene-orbit orbit-two"><span className="orbit-node node-lime" /></div><div className="scene-core"><div className="core-screen"><div className="screen-top"><span /><span /><span /></div><div className="screen-code"><b>system.trace()</b><br /><i>component_id</i>: <strong>"PRV-0729"</strong><br /><i>signal</i>: <strong>"online"</strong><br /><i>stack</i>: [<strong>"AI"</strong>, <strong>"IOT"</strong>]<br /><i>status</i>: <strong>"building"</strong></div></div></div><div className="scene-label label-top">/ neural systems <span>●</span></div><div className="scene-label label-bottom">TRACE / 07:29:26</div></div>
          <a className="scroll-cue" href="#about"><span>SCROLL TO EXPLORE</span><ArrowDown size={15} /></a>
        </section>

        <section id="about" className="neo-section section-pad recruiter-anchor"><div className="section-heading"><p className="section-kicker">02 / ABOUT THE BUILDER</p><h2>Practical systems.<br /><span>Curious mind.</span></h2></div><div className="about-grid"><div className="about-lead"><p>I’m a Computer Science Engineering student focused on turning technical fundamentals into practical, usable products.</p><p className="muted-copy">My work spans software development, data structures and algorithms, AI/ML exploration, and IoT-oriented systems. I enjoy understanding how pieces connect—from the interface and API to the database, device, or model behind it.</p><div className="fact-strip"><div><strong>8.36</strong><span>CGPA / 6TH SEM</span></div><div><strong>03</strong><span>FULL-STACK APPS</span></div><div><strong>2027</strong><span>GRADUATION TARGET</span></div></div></div><div className="about-card glass-card"><div className="card-topline"><span>profile.signal</span><span className="live-tag">LIVE</span></div><div className="signal-bars"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><p className="mono-note">Learning continuously. Shipping practically.<br />Searching for the next meaningful problem.</p><div className="about-tags"><span>SOFTWARE</span><span>AI / ML</span><span>IOT</span><span>DSA</span></div></div></div></section>

        <section id="skills" className="neo-section skills-section section-pad recruiter-anchor"><div className="section-heading split-heading"><div><p className="section-kicker">03 / THE TOOLKIT</p><h2>Skills that connect<br /><span>ideas to outcomes.</span></h2></div><p className="heading-note">No inflated percentages.<br />Just tools I use, study,<br />and build with.</p></div><div className="skills-grid">{skillGroups.map(({ title, icon: Icon, color, items }) => <article key={title} className={`skill-card color-${color}`}><div className="skill-icon"><Icon size={20} /></div><div><h3>{title}</h3><div className="skill-items">{items.map(item => <span key={item}>{item}</span>)}</div></div><span className="card-index">0{skillGroups.findIndex(group => group.title === title) + 1}</span></article>)}</div></section>

        <section id="experience" className="neo-section section-pad recruiter-anchor"><div className="section-heading"><p className="section-kicker">04 / EXPERIENCE</p><h2>Building the<br /><span>trajectory.</span></h2></div><div className="timeline"><div className="timeline-line" /><article className="timeline-item"><span className="timeline-dot" /><div className="timeline-date">2023 — 2027 <b>CURRENT</b></div><h3>B.Tech in Computer Science & Engineering</h3><p className="timeline-org">CMR College of Engineering and Technology · Hyderabad</p><p>Developing a foundation across software engineering, data structures, DBMS, operating systems, networks, AI/ML, and practical project work.</p><div className="timeline-tags"><span>ACADEMIC PATH</span><span>CGPA 8.36</span></div></article><article className="timeline-item placeholder-item"><span className="timeline-dot muted-dot" /><div className="timeline-date">NEXT ENTRY <b>PLACEHOLDER</b></div><h3>Internship / technical experience</h3><p className="timeline-org">Details to be added</p><p>This space is reserved for verified internships, training, work experience, responsibilities, technologies, and measurable contributions when available.</p><div className="timeline-tags"><span>CONTENT READY</span><span>ADD YOUR DETAIL</span></div></article></div></section>

        <section id="projects" className="neo-section projects-section section-pad recruiter-anchor"><div className="section-heading split-heading"><div><p className="section-kicker">05 / FEATURED PROJECT</p><h2>Where ideas meet<br /><span>traceability.</span></h2></div><p className="heading-note">A concept for durable railway component identity—designed for inspection, maintenance, and accountability.</p></div><article className="featured-project glass-card"><div className="featured-project-copy"><div className="project-meta"><span>01 / SYSTEM CONCEPT</span><span className="project-status"><span className="pulse-dot" /> AI + IOT</span></div><h3>AI-Powered Railway Track Fitting Identification & Traceability System</h3><p>An AI-driven laser/QR-based identification system for railway track fittings. It is designed to give each component a durable identity and make manufacturing information, installation details, inspection records, and maintenance history easier to access.</p><div className="project-actions"><a href="#contact" className="neo-button primary">Discuss this project <ArrowRight size={16} /></a><span className="project-note">PROJECT DETAILS / CONCEPT STAGE</span></div></div><div className="trace-visual"><div className="trace-visual-grid" /><div className="trace-scan-ring" /><div className="trace-chip"><span>PRV</span><b>0729</b><small>TRACK FITTING</small></div><div className="trace-readout"><span>IDENTITY / VERIFIED</span><strong>QR → AI → DB</strong></div></div><div className="trace-flow">{railwayStages.map((stage, index) => <div className="trace-stage" key={stage}><span className="stage-number">0{index + 1}</span><span>{stage}</span>{index < railwayStages.length - 1 && <ArrowRight className="flow-arrow" size={14} />}</div>)}</div></article><div className="project-grid">{projectCards.map(project => <article key={project.title} className="project-card"><div className="project-card-top"><span>{project.eyebrow}</span><span>↗</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="project-proof"><CheckCircle2 size={14} /> {project.proof}</div><div className="project-tags">{project.stack.map(item => <span key={item}>{item}</span>)}</div><a href={project.href} target="_blank" rel="noreferrer" className="project-link">View on GitHub <ArrowRight size={14} /></a></article>)}<article className="project-card placeholder-card"><div className="project-card-top"><span>02 / MORE PROJECTS</span><span>+</span></div><h3>Your next build</h3><p>Placeholder slot for another verified project, live demo, contribution, or case study that you want recruiters to inspect.</p><div className="placeholder-line" /><span className="project-note">ADD PROJECT DETAILS LATER</span></article></div></section>

        <section id="education" className="neo-section compact-section section-pad recruiter-anchor"><div className="section-heading"><p className="section-kicker">06 / EDUCATION</p><h2>Foundations<br /><span>in progress.</span></h2></div><div className="education-card glass-card"><div className="education-icon"><GraduationCap size={26} /></div><div><p className="section-kicker">2023 — 2027 · BACHELOR OF TECHNOLOGY</p><h3>Computer Science & Engineering</h3><p>CMR College of Engineering and Technology, Hyderabad</p><div className="education-meta"><span>CGPA <b>8.36</b> / upto 6th sem</span><span>Relevant: DSA · DBMS · OS · Networks</span></div></div></div></section>

        <section id="achievements" className="neo-section achievements-section section-pad recruiter-anchor"><div className="section-heading split-heading"><div><p className="section-kicker">07 / VERIFIED SIGNALS</p><h2>Small wins.<br /><span>Real proof.</span></h2></div><p className="heading-note">Only verified resume information appears here. No inflated counters, no invented awards.</p></div><div className="achievement-grid"><article className="achievement-card"><ShieldCheck size={21} /><span>CERTIFICATION</span><h3>Salesforce Agentforce Specialist</h3><p>Salesforce · Issued Dec 2025 · Credential ID 7319698</p></article><article className="achievement-card"><Network size={21} /><span>CERTIFICATION</span><h3>Networking Basics</h3><p>Cisco Networking Academy · Issued Jan 2026</p></article><article className="achievement-card"><Code2 size={21} /><span>CODING PRACTICE</span><h3>Consistent problem solving</h3><p>Actively solving problems on LeetCode and GeeksforGeeks to strengthen data structures and algorithms.</p></article><article className="achievement-card"><Zap size={21} /><span>BUILDING</span><h3>Three full-stack applications</h3><p>Projects spanning event booking, CRM workflows, and regional language translation.</p></article></div></section>

        <section id="profiles" className="neo-section profiles-section section-pad recruiter-anchor"><div className="section-heading"><p className="section-kicker">08 / CODING PROFILES</p><h2>Find the work<br /><span>in the wild.</span></h2></div><div className="profile-grid">{profileLinks.map(({ label, href, icon: Icon }) => <a key={label} className="profile-card" href={href} target="_blank" rel="noreferrer"><Icon size={20} /><div><span>{label}</span><small>{label === "CodeChef" ? "Profile link provided · dashboard" : "Open profile ↗"}</small></div><ArrowRight size={15} /></a>)}</div></section>

        <section id="resume" className="resume-band section-pad recruiter-anchor"><div><p className="section-kicker">09 / THE SHORT VERSION</p><h2>Want to know more<br />about my work?</h2></div><a href="/manus-storage/MYRESUME_69e3b508.pdf" target="_blank" rel="noreferrer" className="neo-button primary">Download resume <Download size={17} /></a></section>

        <section id="contact" className="neo-section contact-section section-pad recruiter-anchor"><div className="contact-grid"><div><p className="section-kicker">10 / OPEN CHANNEL</p><h2>Let’s ship something<br /><span>inspectable together.</span></h2><p className="contact-copy">Have a project, internship, or technical problem worth exploring? Send a short brief and I’ll respond by email.</p><div className="contact-links"><a href="mailto:praveenchowhan1729@gmail.com"><Mail size={16} /> praveenchowhan1729@gmail.com</a><a href="https://github.com/Chowhan-Praveen" target="_blank" rel="noreferrer"><Github size={16} /> github.com/Chowhan-Praveen</a><a href="https://www.linkedin.com/in/chowhan-praveen-498b0b33b" target="_blank" rel="noreferrer"><Linkedin size={16} /> LinkedIn profile</a></div></div><form className="contact-form glass-card" onSubmit={submitContact}><div className="form-label"><Terminal size={15} /> message.compose()</div><label htmlFor="contact-name">Name</label><input id="contact-name" required placeholder="Your name" /><label htmlFor="contact-email">Email</label><input id="contact-email" required type="email" placeholder="you@example.com" /><label htmlFor="contact-message">Message</label><textarea id="contact-message" required rows={4} placeholder="What are you building?" /><button className="neo-button primary" type="submit">{messageSent ? "Message noted" : "Send message"} <Send size={15} /></button>{messageSent && <p className="form-success">Thanks—please complete the conversation by email.</p>}</form></div></section>
      </main>

      <footer className="neo-footer"><span>© 2026 PRAVEEN CHOWHAN</span><span className="footer-status"><span className="pulse-dot" /> SYSTEM ONLINE</span><span>BUILT WITH CURIOSITY / SHIPPED WITH CARE</span></footer>
      <button className="ask-launcher" onClick={() => setAssistantOpen(!assistantOpen)} aria-expanded={assistantOpen}><Bot size={18} /> Ask Praveen</button>
      {assistantOpen && <aside className="assistant-panel glass-card"><div className="assistant-header"><span><Bot size={16} /> ASK PRAVEEN</span><button onClick={() => setAssistantOpen(false)} aria-label="Close assistant"><X size={16} /></button></div><p>This assistant shell is ready for a real AI connection. It will eventually answer questions about skills, projects, education, experience, technologies, resume, and contact information.</p><form onSubmit={submitAssistantQuestion}><input value={assistantQuestion} onChange={(event) => setAssistantQuestion(event.target.value)} placeholder="Ask about the portfolio..." aria-label="Ask about the portfolio" /><button aria-label="Send question"><Send size={15} /></button></form>{assistantQuestion && <small className="assistant-note">No AI backend is connected yet. Use the contact channel for a real answer.</small>}</aside>}
    </div>
  );
}
